---

- name: create the network cloudformation stack
  cloudformation:
    stack_name: "xerian-dns"
    state: "present"
    region: "eu-central-1"
    disable_rollback: true
    template: "roles/aws-dns/files/dns-cloudformation-template.yml"
    template_parameters:
      EnvironmentName: Xerian
      HostedZoneName: xerian.com

    tags:
      Stack: "xerian-dns"

    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
